### ISSUE TITLE
Building CPP Executables Tutorial Issue

### ISSUE THREAD

**Issue by grasshopper47** [gradle-guides/building-cpp-applications#13]
https://guides.gradle.org/building-cpp-applications/

Section "Add Source Code" says: 

$ mkdir src/main/cpp

and place a main.cpp and a greeting.**hpp** within.

--------------------------------------------------------------
_src/main/cpp/main.cpp_
--------------------------------------------------------------
#include "greeting.**h**" // should be **.hpp** 

#include <iostream>  

int main(int argc, char** argv) {
  std::cout << greeting << std::endl;
  return 0;
}
-------------------------------------------------------------
Output from gradlew assemble:

> Task :compileDebugCpp FAILED
main.cpp
C:\cpp-executable\src\main\cpp\main.cpp(1): fatal error C1083: Cannot open include file: 'greeting.h': No such file or directory

FAILURE: Build failed with an exception.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #289](https://github.com/gradle/guides/issues/289) via [**ZenHub**](https://www.zenhub.com/)
