### ISSUE TITLE
Outdated URL on guides.gradle.com

### ISSUE THREAD

**Issue by Frederikam** [gradle-guides/building-cpp-applications#14]
This url at https://guides.gradle.org is outdated:
![image](https://user-images.githubusercontent.com/2582617/61064339-df501200-a401-11e9-8ad0-3f1b985db58b.png)
It leads to https://guides.gradle.org/building-cpp-executables/ (404)
It should be https://guides.gradle.org/building-cpp-applications/

The link text should probably also be renamed.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #292](https://github.com/gradle/guides/issues/292) via [**ZenHub**](https://www.zenhub.com/)
